### ISSUE TITLE
when pw is too short it exposes key to front end in console error

### ISSUE THREAD

**Issue by illuminatedspace** [illuminatedspace/automagically#48]
Seems to be problem with firebase.auth. Not sure how to fix it. Haven't found any documentation to fix it online.

**Comment by illuminatedspace** [comment]
According to a Firebase developer, it's ok if the key is exposed. No one can do anything they don't have permission for

**Comment by luisamiranda** [comment]
Should we call this done now, because google is skynet and that's ok?
